name: sidekick.support
favicon: null
layout_spectrum: 0.21246652491390705
typography_spectrum: 0.7566766042727977
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7841264687012881
  lightness: 0.8674741939175874
  saturation: 0.5584323513321579
  rhythmicContrast: 0.6576948626898229
purpose: []
